### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by igitur** [ClosedXML/ClosedXML.Report#1]
Please create a NuGet package and add installation instructions in the README.

**Comment by b0bi79** [comment]
Thanks. Yes, I know that. Now I don't have time. A little bit later.

**Comment by b0bi79** [comment]
Hi, Francois.I created the Nuget package and publish it. I also tested ClosedXML.Report with ClosedXML v0.91.0-beta2, everything works fine. Thank you. 10.12.2017, 10:18, "Francois Botha" <notifications@github.com>:Please create a NuGet package and add installation instructions in the README.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.   -----------------With Regards, Alex.
