### ISSUE TITLE
 How can I make a subrange into the same row group?

### ISSUE THREAD

**Issue by BernieSW** [ClosedXML/ClosedXML.Report#171]
I am currently creating a report of the desired type with reference to the "Subrange" template.
 If look at the Subranges_Simple_tMD1 example, I can see that it is divided into the order Customer => Orders => Items.
cut means a single customer
ord means a single order
it means a single item
desc means a some description
no means a number
 The output what I am trying to do is as follows.
|       |   A1    |   B1    |    C1     |   D1   |    E1    |
| :---: | :-----: | :-----: | :-------: | :----: | :------: |
|   1   | cut1.no | ord1.no | ord1.desc | it1.no | it1.desc |
|   2   |         |         |           | it2.no | it2.desc |
|   3   |         | ord2.no | ord2.desc | it1.no | it1.desc |
|   4   |         |         |           | it2.no | it2.desc |
|   5   | cut2.no | ord1.no | ord1.desc | it1.no | it1.desc |
|   6   |         |         |           | it2.no | it2.desc |
|   7   |         | ord2.no | ord2.desc | it1.no | it1.desc |
|   8   |         |         |           | it2.no | it2.desc |

the empty cell is merged with the cell directly above it.
 I tried to use Group Merge2, but excluded "no" or "desc" because the information in the next row may be duplicated.

How can I?

**Comment by b0bi79** [comment]
You will have to change the model so that item has a link to the order, and the order has a link to the customer. Then you can use the following template.

|        |   A1  |   B1    |    C1     |   D1   |    E1    | F1 |
| :---: |  :---:  | :-----: | :-----: | :-------: | :----: | :------: | 
|   1   |          | item.order.customer.no | item.order.no | item.order.desc | item.no | item.desc |
|   2   |          | `<<group MergeLabels=Merge2>>`  | `<<group MergeLabels=Merge2>>` | `<<group MergeLabels=Merge2>>` |  |  |
