### ISSUE TITLE
Non-repeatable header

### ISSUE THREAD

**Issue by TarasBorovyk** [ClosedXML/ClosedXML.Report#224]
I have area which is vertical, and includes horizontal (nested) area. In horizontal area, headers are repeatable horizontlly, which is ok for me. But, Is there the way to mark headers in vertical area as fixed, for them not to repeat, just data which is 2 rows below.

Template: 
[template-output (1).xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/6860713/template-output.1.xlsx)
Result:
[template-result.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/6860715/template-result.xlsx)
Code used(txt):
[code.txt](https://github.com/ClosedXML/ClosedXML.Report/files/6860725/code.txt)

**Comment by b0bi79** [comment]
So that the header is not repeated, it should not be included in the range. But at the same time, you need a horizontal heading to be built.
I changed your template and modified your code:
- LoanProperty range changed to ($A$3:$S$4)
- LoanProperty_Deeds range changed to ($K$3:$S$3)
- added DeedHeader range ($K$1:$S$2)
- added the variable `template.AddVariable("DeedHeader", loanProperties[0].Deeds);`

**Comment by TarasBorovyk** [comment]
@b0bi79 ok, thx a lot, this fixed my issue. But, I also found another bug. I have subcollection Deeds, but also there is collection Mortgages.
And, If Deeds collection in any LoanProperty has Count() of items not same, then it occupies area for Mortgages, which goes after Deeds. Is if possible to fix? I'm fixing it by adding default values.

**Comment by b0bi79** [comment]
ClosedXML.Report cannot solve this. You must make sure that all Deeds collections have the same number of objects.
