### ISSUE TITLE
Refer to <<sum>> cell in formula

### ISSUE THREAD

**Issue by L00maca** [ClosedXML/ClosedXML.Report#42]
I've been trying to create a table that takes the totals of each column from another table (the <<sum>> cell) to perform other calculation starting from there.

Pointing to the cell using an excel formula (like "=Sheet1!A5") keeps pointing at the same cell in the final file, no matter how many rows have been added above. Escaping the formula ("&=Sheet1!A5") ends in the same result. 
Trying to calculate the ending position of the cell using the knowledge of the number of rows that will be added ends up moving the cell down by about (but not exactly) double the amount of rows.

Either I have failed to find in the wiki the way to accomplish this, or it is not possible to implement in the current version so I'd love to have something to accomplish this as a feature.

**Comment by b0bi79** [comment]
The fact is that you can not refer inside the range. The range is a dynamically changing structure and it is impossible to predict what it will be in the final document.
I'll think about how we can exclude the summary row from this restriction.

**Comment by Pankraty** [comment]
I think the reason is that ClosedXML.Report in the current version turns off rows/columns shifting events. With this formulas are not shifted as they should be. After we upgrade to ClosedXML 0.93+ the issue will probably go away. At least I hope so. 
And I really wish I had time to finish with #35 at last...

**Comment by b0bi79** [comment]
No, the reason is that the link points to the inside of the range, and ClosedXML.Report pushing the boundaries of the range adds new rows to the existing ones. That is lines are added below the row with totals and therefore the link is not recalculated. I now want to make the lines added over the range..

**Comment by b0bi79** [comment]
Yes, it helped, but other tests broke down. It is necessary to understand ...

**Comment by b0bi79** [comment]
Done
