### ISSUE TITLE
Using Template containing certain Excel 2013 conditional formatting selections causes NullReferenceException

### ISSUE THREAD

**Issue by DukeOfDelmar** [ClosedXML/ClosedXML.Report#48]
1. Create a template in Excel with a vertical table with a detail cell formatted with the "Color Scales -> Red Yelllow Green Color Scale" selection from the Conditional Formatting menu.
2. Attempt to apply the template.
3. Exception occurs:
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=ClosedXML.Report
  StackTrace:
   at ClosedXML.Report.Excel.XlExtensions.<>c.<ReplaceCFFormulaeToR1C1>b__30_0(KeyValuePair`2 v)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ClosedXML.Report.Excel.XlExtensions.ReplaceCFFormulaeToR1C1(IXLWorksheet worksheet)
   at ClosedXML.Report.XLTemplate.Generate()
 ...

**Comment by b0bi79** [comment]
@DukeOfDelmar can you attach your template and code sample please? I can not reproduce this problem.

**Comment by DukeOfDelmar** [comment]
https://github.com/DukeOfDelmar/CondFormatIssue

**Comment by b0bi79** [comment]
@DukeOfDelmar Sorry for long answer. You have created the wrong template. In your template, I added a named range "details" and everything began to work. Here is a modified template.
[Broken.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/3077147/Broken.xlsx)

**Comment by MikeInSwitzerland** [comment]
I'm having the same issue with ClosedXml.Report v0.2.4 and the bug is still present in the latest code (in October 2023).

With a new Excel template file, it crashes with a null pointer exception in the **XLTemplate.Generate()** function:
`iXLWorksheet.ReplaceCFFormulaeToR1C1();`

`Object reference not set to an instance of an object. `

Looking at line 338 of the code... 
https://github.com/ClosedXML/ClosedXML.Report/blob/develop/ClosedXML.Report/Excel/XlExtensions.cs

... it seems to be this line...
`foreach (var v in format.Values.Where(v => v.Value.IsFormula).ToList())`

If one of the cells in the Conditional Formating range is blank (i.e. _null_), then the code is doing **null.ToList()** and crashing.  

And in my code, I was finding that my 1-column, 22-row Range was actually showing just _three_ values in the "format.Values" array...  two of these values were null, but in the spreadsheet, all 22 cells _did_ have data in them.

There is a REALLY dumb way to get around this bug.
On the worksheet which is causing this issue, put a Pivot table.  It doesn't matter what data it's referring to, just put a Pivot table in there.  And hide it, if you want to.

Why does this make a difference ?
Because the buggy ClosedXml code is only looking for Custom Formatting values in Worksheets which are visible *and* which don't contain a Pivot table in them.   

```
IXLWorksheet[] array = Workbook.Worksheets.Where((IXLWorksheet sh) => sh.Visibility == XLWorksheetVisibility.Visible 
        && !sh.PivotTables.Any()).ToArray();
foreach (IXLWorksheet iXLWorksheet in array)
{
    iXLWorksheet.ReplaceCFFormulaeToR1C1();    //  This is the line which throws an exception
    _interpreter.Evaluate(iXLWorksheet.AsRange());
    iXLWorksheet.ReplaceCFFormulaeToA1();
}
```

(Don't look at me like that... I didn't write this code...  It doesn't make any sense to me either !!)

The problem with this solution is that, even though we don't want/care about this Pivot table, it will now make Excel display an annoying message when you open the Excel file:

_"There's already data in [MikesExcel.xlsx]MikesWorksheet.  Do you want to replace it ?"_

You can disable this message, for all Excel files, by following these steps.
https://www.excelhowto.com/macros/how-to-disable-theres-already-data-here-do-you-want-to-replace-it-warning/


The proper way to fix this is to modify line 338 of _ClosedXML.Report\Excel\XlExtensions.cs_, to check for nulls:

`foreach (var v in format.Values.Where(v => v.Value != null && v.Value.IsFormula).ToList())`
