### ISSUE TITLE
Creating a report with 273567 records giving an out of memory exception

### ISSUE THREAD

**Issue by SigmaSoftSol** [ClosedXML/ClosedXML.Report#68]
Hello Team,
  I am exporting a huge bunch of list data to the excel using the templates.  the data contains more than 200000 records.  When I am trying to Generate it is is giving out of memory exception.
How can I resolve this issue.

**Comment by b0bi79** [comment]
The latest version of ClosedXML, which is used to create Excel files, has done a lot of work to optimize memory and performance.
Now I am working on the transition to the new version, quite a lot of work has already been done, but still some tests do not pass. I can give you this unfinished version, so that you can check if it helps you or not.

**Comment by SigmaSoftSol** [comment]
Yes Please.  I will test it from end also.  And what would be the tentative date for the updated version to be available.

**Comment by b0bi79** [comment]
Here it is [ClosedXml.Report.zip](https://github.com/ClosedXML/ClosedXML.Report/files/2772763/ClosedXml.Report.zip)

**Comment by SigmaSoftSol** [comment]
Thanks for the Version.  I will test it ad will update you.

**Comment by SigmaSoftSol** [comment]
Hi,
   The dll's that you have shared with me resolved the issue.

**Comment by b0bi79** [comment]
Great.
