### ISSUE TITLE
RowHeight is not set correctly in added rows

### ISSUE THREAD

**Issue by BenKmann** [ClosedXML/ClosedXML.Report#88]
The documentation says "Styles from the template are applied to the inserted cells."
But the rowheight of each row is apparently not taken from my contentarrea, but from the existing row. Apparently it just moves in the next row, instead of adding new rows.

If you look at my Template you see, that the rowheight in Row 7 is pretty small.
![template](https://user-images.githubusercontent.com/12639595/59447890-5e9ef580-8e04-11e9-963a-453d4759b9c0.PNG)

But if you look at the resulting document, you see in row 11 for example, that he took the rowheight of the row 11 that was in the template.
![document](https://user-images.githubusercontent.com/12639595/59447822-3a431900-8e04-11e9-8d86-c179881b0eb9.PNG)

That way he kills the formatting of every row below the defined Area and kills the formatting inside the Area.

I also added the Template if it helps. 
[buggy.xlsx](https://github.com/ClosedXML/ClosedXML.Report/files/3287065/buggy.xlsx)

I can also submit the code to generate the undesired behaviour if you need it.

I use the newest available Versions
  "ClosedXML" version="0.95.0-beta1" targetFramework="net452"
  "ClosedXML.Report" version="0.2.0-beta1" targetFramework="net452"

**Comment by b0bi79** [comment]
Thank. In the near future I will check it out.

**Comment by Pankraty** [comment]
To be honest, I do not see how to solve the problem nicely. In the current implementation, the vertical table grows by inserting a range under the template row. Inserting rectangular ranges does not affect row height - either in ClosedXML or in Excel:
![InsertRange](https://user-images.githubusercontent.com/19576939/60670469-c5eb1b00-9e81-11e9-9a0a-a602e6984c9c.gif)

On the other hand, if ClosedXML.Report would insert _rows_ instead of _ranges_ this would affect other data on the worksheet. Consider having another table to the right of the one generated by ClosedXML. One would expect this table to stay untouched, but if we'd insert rows that would produce the incorrect result:
![image](https://user-images.githubusercontent.com/19576939/60670869-c6d07c80-9e82-11e9-9ade-008aa2e17c0c.png)
And if there would be another dynamically generated table, they would affect each other even more badly. 

As for your issue with row heights, we also had such before (even before migrating to ClosedXML.Report).  I think the best you can do - is to reset all row heights to `null` (programmally, or by editing XMLs inside the XLSX;  I am not aware of the way of doing this via UI) and the rely on auto-sizing feature. It is not perfect but is at least something.

**Comment by BenKmann** [comment]
Wow thanks for the great Explanation. I agree, it is Excel default behaviour. 
Ok i will change the rowheight by Code then. 
Thanks again for looking into it.

**Comment by b0bi79** [comment]
You also have the ability to process the document after it is generated with ClosedXML.Report.
Thank you, Alexey, for your help.

**Comment by BenKmann** [comment]
Hmm the only thing i don't Understand is, shoudn't the Tag RowsFit help me here, it should correct the RowHeight. https://closedxml.github.io/ClosedXML.Report/docs/en/More-options

But it won't correct these Issues for me, if I put it in Column A of the Table.
